"""Streamlit persona editor — run: streamlit run tools/persona_editor/app.py"""
from __future__ import annotations

import sys
from pathlib import Path

import numpy as np
import pandas as pd
import streamlit as st

sys.path.insert(0, str(Path(__file__).parent.parent))
from personas import PERSONAS, PRICING  # noqa: E402


def _personas_to_python(personas_list: list[dict]) -> str:
    header = '''"""Mock customer personas (generated by persona_editor).
Edit via:  streamlit run tools/persona_editor/app.py
"""
from dataclasses import dataclass
from typing import Literal


@dataclass
class Persona:
    external_id: str
    display_name: str
    archetype: Literal["whale", "healthy", "marginal", "unprofitable", "churning", "new"]
    monthly_revenue_usd: float
    monthly_budget_usd: float | None
    runs_per_day_mean: float
    runs_per_day_stddev: float
    cost_per_run_mean: float
    cost_per_run_stddev: float
    workflows: dict[str, float]
    models: dict[str, float]
    anomaly_rate: float = 0.0
    avg_input_tokens: int = 800
    avg_output_tokens: int = 200


PRICING = {
    "gpt-4o-mini":       {"input": 0.150,  "output": 0.600},
    "gpt-4o":            {"input": 2.500,  "output": 10.000},
    "claude-3-5-sonnet": {"input": 3.000,  "output": 15.000},
    "claude-3-5-haiku":  {"input": 0.800,  "output": 4.000},
    "claude-3-opus":     {"input": 15.000, "output": 75.000},
}


PERSONAS = [
'''
    lines = [header]
    for p in personas_list:
        lines.append("    Persona(")
        for k, v in p.items():
            lines.append(f"        {k}={v!r},")
        lines.append("    ),")
    lines.append("]\n")
    return "\n".join(lines)


st.set_page_config(page_title="AgentCOGS Persona Editor", layout="wide")

if "personas" not in st.session_state:
    st.session_state.personas = [{**p.__dict__} for p in PERSONAS]

st.sidebar.title("Personas")
selected_idx = st.sidebar.radio(
    "Edit",
    options=range(len(st.session_state.personas)),
    format_func=lambda i: (
        f"{st.session_state.personas[i]['display_name']} "
        f"({st.session_state.personas[i]['archetype']})"
    ),
)

col_a, col_b = st.sidebar.columns(2)
if col_a.button("➕ Add", use_container_width=True):
    st.session_state.personas.append({
        "external_id": f"new_persona_{len(st.session_state.personas)}",
        "display_name": "New Persona",
        "archetype": "new",
        "monthly_revenue_usd": 1000.0,
        "monthly_budget_usd": 500.0,
        "runs_per_day_mean": 50.0,
        "runs_per_day_stddev": 15.0,
        "cost_per_run_mean": 0.05,
        "cost_per_run_stddev": 0.02,
        "workflows": {"default": 1.0},
        "models": {"gpt-4o-mini": 1.0},
        "anomaly_rate": 0.0,
        "avg_input_tokens": 800,
        "avg_output_tokens": 200,
    })
    st.rerun()

if col_b.button("🗑️ Delete", use_container_width=True):
    if len(st.session_state.personas) > 1:
        st.session_state.personas.pop(selected_idx)
        st.rerun()

p = st.session_state.personas[selected_idx]
st.title(f"📝 {p['display_name']}")
st.caption(f"Archetype: **{p['archetype']}** · External ID: `{p['external_id']}`")

tab1, tab2, tab3, tab4 = st.tabs([
    "Identity & Revenue", "Usage Shape", "Workflows & Models", "Preview"
])

with tab1:
    c1, c2 = st.columns(2)
    p["external_id"] = c1.text_input("External ID", p["external_id"])
    p["display_name"] = c2.text_input("Display name", p["display_name"])
    archetypes = ["whale", "healthy", "marginal", "unprofitable", "churning", "new"]
    p["archetype"] = c1.selectbox("Archetype", archetypes, index=archetypes.index(p["archetype"]))
    st.subheader("Money")
    c3, c4 = st.columns(2)
    p["monthly_revenue_usd"] = c3.number_input(
        "Monthly revenue ($)", value=float(p["monthly_revenue_usd"]), min_value=0.0, step=50.0
    )
    budget_enabled = c4.checkbox("Has budget cap?", value=p["monthly_budget_usd"] is not None)
    if budget_enabled:
        p["monthly_budget_usd"] = c4.number_input(
            "Monthly budget ($)",
            value=float(p["monthly_budget_usd"] or 100),
            min_value=0.0,
            step=50.0,
        )
    else:
        p["monthly_budget_usd"] = None

with tab2:
    c1, c2 = st.columns(2)
    p["runs_per_day_mean"] = c1.slider(
        "Mean runs/day", 0.0, 2000.0, float(p["runs_per_day_mean"]), step=5.0
    )
    p["runs_per_day_stddev"] = c2.slider(
        "Stddev runs/day", 0.0, 500.0, float(p["runs_per_day_stddev"]), step=5.0
    )
    c3, c4 = st.columns(2)
    p["cost_per_run_mean"] = c3.number_input(
        "Mean cost/run ($)", value=float(p["cost_per_run_mean"]), min_value=0.0, format="%.4f"
    )
    p["cost_per_run_stddev"] = c4.number_input(
        "Stddev cost/run ($)", value=float(p["cost_per_run_stddev"]), min_value=0.0, format="%.4f"
    )
    c5, c6 = st.columns(2)
    p["avg_input_tokens"] = int(
        c5.number_input("Avg input tokens", value=int(p["avg_input_tokens"]), min_value=0, step=100)
    )
    p["avg_output_tokens"] = int(
        c6.number_input("Avg output tokens", value=int(p["avg_output_tokens"]), min_value=0, step=50)
    )
    p["anomaly_rate"] = st.slider(
        "Anomaly day probability", 0.0, 0.20, float(p["anomaly_rate"]), step=0.01
    )

with tab3:
    wf_df = pd.DataFrame([{"workflow_id": k, "probability": v} for k, v in p["workflows"].items()])
    edited_wf = st.data_editor(wf_df, num_rows="dynamic", use_container_width=True, key=f"wf_{selected_idx}")
    wf_sum = edited_wf["probability"].sum()
    if abs(wf_sum - 1.0) > 0.01:
        st.warning(f"Workflow probabilities sum to {wf_sum:.2f} (should be 1.00)")
    p["workflows"] = dict(zip(edited_wf["workflow_id"], edited_wf["probability"]))

    model_df = pd.DataFrame([{"model": k, "probability": v} for k, v in p["models"].items()])
    edited_models = st.data_editor(
        model_df,
        num_rows="dynamic",
        use_container_width=True,
        column_config={"model": st.column_config.SelectboxColumn(options=list(PRICING.keys()))},
        key=f"models_{selected_idx}",
    )
    m_sum = edited_models["probability"].sum()
    if abs(m_sum - 1.0) > 0.01:
        st.warning(f"Model probabilities sum to {m_sum:.2f} (should be 1.00)")
    p["models"] = dict(zip(edited_models["model"], edited_models["probability"]))

with tab4:
    monthly_runs = p["runs_per_day_mean"] * 30
    monthly_cost = monthly_runs * p["cost_per_run_mean"]
    margin = (
        (p["monthly_revenue_usd"] - monthly_cost) / p["monthly_revenue_usd"] * 100
        if p["monthly_revenue_usd"] > 0
        else 0
    )
    c1, c2, c3 = st.columns(3)
    c1.metric("Est. monthly runs", f"{monthly_runs:,.0f}")
    c2.metric("Est. monthly AI cost", f"${monthly_cost:,.2f}")
    c3.metric("Est. gross margin", f"{margin:.1f}%" if p["monthly_revenue_usd"] > 0 else "—")
    sample = np.random.normal(p["cost_per_run_mean"], p["cost_per_run_stddev"], 1000).clip(0)
    st.bar_chart(pd.Series(sample).value_counts(bins=30).sort_index())

st.divider()
st.subheader("💾 Export")
col1, col2, col3 = st.columns(3)
python_out = _personas_to_python(st.session_state.personas)

if col1.button("📋 Copy as Python", use_container_width=True):
    st.code(python_out, language="python")

if col2.download_button(
    "📄 Download personas.py",
    python_out,
    file_name="personas.py",
    mime="text/x-python",
    use_container_width=True,
):
    pass

if col3.button("💾 Save in place", use_container_width=True):
    Path(__file__).parent.parent.joinpath("personas.py").write_text(python_out)
    st.success("Saved → tools/personas.py")
